# Databricks notebook source
extract_priceArea_sql = """ SELECT RS.ROG_ID
,RS.FACILITY_NBR AS aciFacilityId
,CONCAT(RS.ROG_ID, '-', RP.PRICE_AREA_CD) AS priceAreaId
,COALESCE(RS.BANNER_NM, '') AS BANNER_NM
,'' AS priceAreaName
,COALESCE(RP.SECTION_CD, '') AS SECTION_CD
,COALESCE(FC.FACILITY_NM, '') AS FACILITY_NM
,COALESCE(RP.PRICE_AREA_CD, '') AS PRICE_AREA_CD
,COALESCE(RS.DIVISION_ID, '') AS DIVISION_ID
,COALESCE(FA.ADDRESS_LINE1_TXT, '') AS ADDRESS_LINE1_TXT
,COALESCE(FA.ADDRESS_LINE2_TXT, '') AS ADDRESS_LINE2_TXT
,COALESCE(FA.CITY_NM, '') AS CITY_NM
,COALESCE(FA.COUNTRY_CD, '') AS COUNTRY_NM
,COALESCE(FA.POSTAL_ZONE_CD, '') AS POSTAL_ZONE_CD
,COALESCE(FA.LATITUDE_DGR, NUMERIC '0') AS LATITUDE_DGR
,COALESCE(FA.LONGITUDE_DGR, NUMERIC '0') AS LONGITUDE_DGR
,COALESCE(FA.STATE_CD, '') AS STATE_NM
,current_timestamp() AS CREATEDTIMESTAMP
,'Pricing System' AS CREATEDBY
,current_timestamp() AS UPDATEDTIMESTAMP
,'Pricing System' AS UPDATEDBY
 
FROM {0}.udco_ds_locn.RETAIL_STORE RS
 
JOIN {0}.udco_ds_locn.RETAIL_STORE_SECTION_PRICE_AREA RP
ON RP.FACILITY_INTEGRATION_ID = RS.FACILITY_INTEGRATION_ID
AND RP.DW_CURRENT_VERSION_IND = true AND RP.DW_LOGICAL_DELETE_IND = false
AND RS.DW_CURRENT_VERSION_IND = true AND RS.DW_LOGICAL_DELETE_IND = false
 
JOIN {0}.udco_ds_locn.FACILITY_ADDRESS FA
ON FA.FACILITY_INTEGRATION_ID = RS.FACILITY_INTEGRATION_ID
AND FA.DW_CURRENT_VERSION_IND = true AND FA.DW_LOGICAL_DELETE_IND = false
 
JOIN {0}.udco_ds_locn.FACILITY FC
ON FC.ACI_FACILITY_INTEGRATION_ID = RS.FACILITY_INTEGRATION_ID
AND FC.DIVISION_ID = RS.DIVISION_ID
AND FC.DW_CURRENT_VERSION_IND = true AND FC.DW_LOGICAL_DELETE_IND = false

JOIN {0}.udco_ds_locn.FACILITY_DEPARTMENT_SECTION DS
ON DS.SECTION_CD = RP.SECTION_CD
AND DS.FACILITY_INTEGRATION_ID = RP.FACILITY_INTEGRATION_ID
AND DS.DW_CURRENT_VERSION_IND = true AND DS.DW_LOGICAL_DELETE_IND = false 

WHERE RS.ROG_ID IS NOT NULL """
